### ISSUE TITLE
Spike: Increase code examples on the website

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#14]
## Summary
Identify what examples we need for each comp.

NB. reminder to create new ticket for each comp that needs code examples.

## 💬 Description
Increase code examples on the website to give developers more examples on using our code e.g. Cards has no code examples

## 💰 Use value
Make it easier for developers to consume components

**Comment by GCHQ-Developer-112** [comment]
### TODO
- [ ] Breadcrumbs
  - [ ] Slotted Links
  - [ ] Back
  - [ ] Icon
  - [ ] Collapsed

- [ ] Card
  - [ ] Title only
  - [ ] Disabled
  - [ ] Slots example

**Comment by GCHQ-Developer-530** [comment]
**Tasks**

Breadcrumbs
  - [ ] Slotted Links
  - [ ] Back
  - [ ] Icon
  - [ ] Collapsed

Card
  - [ ] Title only
  - [ ] Disabled
  - [ ] Slots example

Checkbox
    - [ ] Hidden label
    - [ ] Helper text
    - [ ] Validation
    - [ ] Indeterminate

Classification banner
    - [ ] Country
    - [ ] Additional selectors

Data entity
    - [ ] Doesn’t currently exist on guidance site, so it needs everything

- [ ] Hero and footer are wrong way around alphabetically in guidance site component menu

Footer
    - [ ] Logo links

Hero
    - [ ] Centre aligned
    - [ ] Long heading
    - [ ] Content centre aligned
    - [ ] Secondary heading
    - [ ] Search
    - [ ] Card right content
    - [ ] Image right content
    - [ ] Background image

Link 
    - [ ] With icon
    - [ ] Dark and light

Loading
    - [ ] Determinate
    - [ ] Sizes
    - [ ] Linear
    - [ ] Light
    - [ ] Changing label
    - [ ] No label

Page header
    - [ ] Breadcrumbs
    - [ ] Component overrides

Radio
    - [ ] Helper text
    - [ ] Validation

Search bar
    - [ ] With options (filtering and no filtering)
    - [ ] Helper text
    - [ ] Hidden label
    - [ ] Disabled state

Select
    - [ ] With clear
    - [ ] With description
    - [ ] Helper text
    - [ ] Custom placeholder
    - [ ] Disabled and disabled options
    - [ ] Hidden label
    - [ ] Groups
    - [ ] Recommended
    - [ ] Validation
    - [ ] Searchable (for all of the above too)

Side nav
    - [ ] Static
    - [ ] Collapsed icons with labels
    - [ ] Slots

Skeleton
    - [ ] Inherited from child
    - [ ] Set height and width
    - [ ] Circle
    - [ ] Text
    - [ ] Light

Stepper
    - [ ] Left aligned
    - [ ] Without step titles
    - [ ] Custom stepper
    - [ ] Custom connector width

Switch
    - [ ] State
    - [ ] Small
    - [ ] Disabled & disabled checked
    - [ ] Helper text
    - [ ] Right adornment

Tab
    - [ ] With icons
    - [ ] Disabled
    - [ ] Dark

Text field
    - [ ] With icon
    - [ ] With Value
    - [ ] Max length
    - [ ] Disabled
    - [ ] Validation
    - [ ] Text area with resize

Top nav
    - [ ] Centre aligned
    - [ ] Content left aligned
